### ISSUE TITLE
RC releases as latest

### ISSUE THREAD

**Issue by danielmariz** [s-panferov/awesome-typescript-loader#110]
Hey mate, just wondering if your last release is reliable, cause is set up as your latest version on npm info, which means it will be automatically updated in fill projects.

Cheers!

**Comment by s-panferov** [comment]
@danielmariz hello. 

If you have something like "^0.16.2" in your `package.json` file, you will never get `0.17.0-rc.x` version by auto-update. You can check this out here http://semver.npmjs.com/.

As for fresh install, e.g. by command `npm install awesome-typescript-loader --save` I think it's ok to install pre-release version, because it's quite stable and you usually don't have any backward compability requirements at this point.
