### ISSUE TITLE
Can't use `escape`

### ISSUE THREAD

**Issue by zwhitchcox** [s-panferov/awesome-typescript-loader#115]
Getting an error when using [escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) which is a function in javascript

It says `Cannot find name 'escape'`.

**Comment by s-panferov** [comment]
@zwhitchcox hello. This is not the loader's issue, because there is no `escape` function in typescript's [lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts) file. I believe it's because of deprecation and vendor nature of the function.

If you really want to use it, you can create `.d.ts` file and define it like that:

```
declare function escape(x: string): string;
```

**Comment by zwhitchcox** [comment]
Oh ok. I didn't realize it had been deprecated.
