### ISSUE TITLE
Typescript 2.0 - react-dom.server.d.ts not found - works in tsloader

### ISSUE THREAD

**Issue by admmasters** [s-panferov/awesome-typescript-loader#224]
Using TS 2.0RC and the new @types typings - specifically node_modules/@types/react-dom/react-dom.server.d.ts does not get found during build - even though the file is clearly there and loads with ts-loader.

**Comment by AlexanderMattoni** [comment]
Having the same issue. Been banging my head against the wall trying to track down the source (error message wasn't very clear) and haven't been able to find a version that works.

**Comment by thrandre** [comment]
More people having the same issue in #205

**Comment by narkowicz** [comment]
I also stumbled on this issue last week. Rather than modifying untracked files in `node_modules` I found that manually adding the problematic path to `"files": [...]` in `tsconfig.json` provides a workaround for the issue.

i.e. `"files": [ "node_modules/@types/react-dom/react-dom.server.d.ts" ]`

`tsconfig.json` supports comments so workaround can be documented, relevant issues linked and a note left to clean up when a fix is implemented.

**Comment by thrandre** [comment]
@narkowicz: That's great! Thanks for sharing.

**Comment by s-panferov** [comment]
I'll take a look soon

**Comment by narkowicz** [comment]
@thrandre That's a shame - these ts / webpack setups can be so idiosyncratic!

**Comment by robmcm** [comment]
Is there a planned release with this patch in? Would be good to get it released and save having to add it as a git dependency in npm. Thanks
