### ISSUE TITLE
Internal namespace modules giving not defined errors.

### ISSUE THREAD

**Issue by apawsey** [s-panferov/awesome-typescript-loader#246]
If I try and use internal modules with namespaces, there doesn't seem to be any dependency created.

For example:
A.ts

```
namespace Test {
  export class A {
    ...
  }
}
```

B.ts

```
import A = Test.A;
export class TestService {
  testMethod() {
    let a = new A;
  }
}
```

Everything compiles and bundles fine, but at runtime I get an error that A is not defined.  Looking at the bundled output, I see the A.ts file as a webpack module, but in the B.ts code, there is no reference to indicate that A.ts should be loaded.  It's like it's assuming the namespace will be globally available.

Have I missed something, perhaps a configuration issue?

EDIT
It will work if I remove the namespace and import like an external module (`import {A} from "./A"`)

**Comment by aggieben** [comment]
I am also trying to work through this issue (in the browser).  I'm using the `/// <reference ...` annotation to make sure `tsc` knows how to order the concatenated output in the bundle (defined by webpack, invoked by ts-loader).  The tooling all seems fine with it, and I can visually verify in the bundle that all the transpiled output is there.  But when the browser loads the bundle, my internal module (namespace) is undefined.

**Comment by s-panferov** [comment]
Hi @apawsey, this loader is designed to work with `ES6` or `CommonJS` modules style and corresponding `moduleResolution: 'node'` option in tsconfig.json. If you use internal typescript modules, there is no way for webpack to know which files should be included into the bundle (because they have no explicit `require` calls).

So you can just use `tsc` to build such bundles.
