### ISSUE TITLE
Build returns with exit code 0 even if there are compilation errors

### ISSUE THREAD

**Issue by komu** [s-panferov/awesome-typescript-loader#26]
If I have a TypeScript file with syntax errors, `webpack --bail` returns exit code 0 instead of producing a non-zero value. If I have a JavaScript file with errors, exit code 1 is returned, as expected.

This seems to be the same issue as andreypopp/typescript-loader#21.

**Comment by s-panferov** [comment]
@komu it looks like the `bail` option is broken in webpack right now

**Comment by s-panferov** [comment]
@komu error is fixed in v0.7.0-rc.0

**Comment by x-yuri** [comment]
From what I can see, it was never fixed in `awesome-typescript-loader`. And I'm not sure what `--bail` has to do with it. I'd say `awesome-typescript-loader` uses Webpack in pretty uncommon way. By making loader succeed at all times (almost). And injecting errors only on [`after-compile`](https://github.com/s-panferov/awesome-typescript-loader/blob/v5.2.0/src/instance.ts#L511) phase. The issue was fixed in [`webpack-2.0.0`](https://github.com/webpack/webpack/commit/0c8d94fa).
