### ISSUE TITLE
'channel closed' on watch

### ISSUE THREAD

**Issue by prencher** [s-panferov/awesome-typescript-loader#287]
Whenever webpack detects a change, the following happens:
```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Object.send (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\checker\send.ts:24:35)
    at Checker.req (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\checker\checker.ts:87:21)
    at Checker.emitFile (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\checker\checker.ts:98:21)
    at transform (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\index.ts:106:29)
    at transformationFunction (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\index.ts:57:44)
    at compiler (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\index.ts:73:30)
    at Object.loader (C:\Projects\Aliso\node_modules\awesome-typescript-loader\src\index.ts:15:18)
    at LOADER_EXECUTION (C:\Projects\Aliso\node_modules\loader-runner\lib\LoaderRunner.js:114:14)
    at runSyncOrAsync (C:\Projects\Aliso\node_modules\loader-runner\lib\LoaderRunner.js:115:4)
```

This is with `awesome-typescript-loader@3.0.0-beta.9` with the simplest of configs:
```
const webpack = require('webpack');
const packageJson = require('./package.json');

module.exports = {
    entry: {
        app: './source/main.ts',
        vendor: Object.keys(packageJson['dependencies']),
    },
    output: {
        path: 'build',
        filename: '[name].js'
    },
    devtool: 'source-map',
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
    },
    module: {
        loaders: [
            { test: /\.json$/, loader: 'json-loader' },
            { test: /\.tsx?$/, loader: 'awesome-typescript-loader' },
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js' })
    ],
};
```

**Comment by drywolf** [comment]
I'm experiencing the same problem when running `webpack --watch` with awesome-typescript-loader

at-loader version: 3.0.0-beta.9
webpack version: 2.1.0-beta.26

**Comment by FrozenPandaz** [comment]
I am also having this issue but only for a larger project.

**Comment by s-panferov** [comment]
Hello everybody. It's very hard to debug things on Windows if you don't have one (virtualized environment don't play well with webpack), so I will appreciate any help with debugging.

And it also will be helpful to know more about your environments:

1. OS version
2. NodeJS version
3. TypeScript version

**Comment by FrozenPandaz** [comment]
Sorry, here is my environment.

OS: Mac OS X El Capitan
Node: 6.9.1
Typescript: 2.1.1

**Comment by prencher** [comment]
Completely forgot to put that on the initial issue, sorry:
* Windows 10
* Node.js 6.9.1
* TypeScript 2.0.10
* Webpack 2.1.0-beta.27

**Comment by drywolf** [comment]
- Windows 10
- Nodejs 4.2.6
- TypeScript 2.1.0-dev.20161011
- Webpack 2.1.0-beta.26

**Comment by FrozenPandaz** [comment]
@s-panferov Has this info helped you reproduce the issue?

**Comment by declandewet** [comment]
I'm also experiencing this problem on the latest Webpack 2 / TypeScript 2 releases (on macOS Sierra - Node 6.x)

I'm not too experienced with child process handling but I think the cause is either that the child process dies too soon or doesn't die at all... These are usually the causes of the "channel closed" error. I've tried playing with hooking on to `SIGHUP` / `SIGTERM` / etc signals in [`checker/checker.js`](checker/checker.js), [`checker/runtime.js`](checker/runtime.js) and [`checker/send.js`](checker/send.js) to try and close the child process with a graceful shutdown but haven't had any luck - I'm afraid the extent of my knowledge in this area isn't of much use here :(

**Comment by s-panferov** [comment]
@FrozenPandaz neither I can reproduce the issue for all this time, nor my colleagues which use the loader.

I think I need to add some debug logging.

**Comment by s-panferov** [comment]
Just published a new version with more error handling. Please try 3.0.0-beta.10 and report errors if any.

**Comment by declandewet** [comment]
@s-panferov Tried it with `3.0.0-beta.10`, the stderr output is the same as before the update.

```
Error: channel closed
...
```

No other errors are being logged. `ts-loader` works, though. 

I put a reproducible case here: https://github.com/declandewet/awesome-ts-loader-bug

Just run `npm run dev` to start the webpack watcher, then change any `.ts` file in `src/` to trigger an incremental build.

**Comment by drywolf** [comment]
I can confirm that I am also getting the error only when I use multiple concurrent builds in webpack.config.js.
If I only export a single build config from webpack.config.js the problem does not occur.

**Comment by s-panferov** [comment]
@declandewet thanks for the example. I'll try to figure it out.

**Comment by s-panferov** [comment]
@declandewet thanks for the investigation. 

I've found the main reason for that behavior. It's because `atl` fails to detect a `--watch` more in the latest `webpack@beta` and kills child processes after a first compilation.

I have several possibilities to fix this:

1. Introduce a webpack plugin to reliably detect `--watch` mode
2. Wait an answer from here https://github.com/webpack/webpack/issues/3460
3. Don't rely on `--watch` mode detection, but this will require `webpack` to wait every time until `TypeScript` finishes its compilation to mark build as `finished` in `--watch` mode.

**Comment by Delagen** [comment]
#304
