### ISSUE TITLE
Please clarify cache hashing

### ISSUE THREAD

**Issue by Offirmo** [s-panferov/awesome-typescript-loader#289]
Thanks for your work !

The question is : can we use the cache feature (.awcache)  on a CI server ?

Can I share the cache between several branches of my codebase ? What is included in the hash of a cache entry ? How does it match / miss ?

In which case should I clear the cache ? (if any) Ex. if I change tsconfig.json or .babelrc, should I manually clear the cache ?

Thanks.

**Comment by s-panferov** [comment]
@Offirmo cache identifier is a hash of file text and also some addinitional variables https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L181-L188

> In which case should I clear the cache ? (if any) Ex. if I change tsconfig.json or .babelrc, should I manually clear the cache ?

Right now you must clear the cache, because `tsconfig.json` and `.babelr` are not mentioned in cacheIdentifier. Maybe I should to reconsider this.

**Comment by Offirmo** [comment]
Thanks !
