### ISSUE TITLE
tsconfig `"declaration": true` doesn't produce declaration files

### ISSUE THREAD

**Issue by QuantumInformation** [s-panferov/awesome-typescript-loader#349]
I did this with ts-loader in the same repo and it works(produces /src)

![image](https://cloud.githubusercontent.com/assets/216566/21911651/975c992e-d919-11e6-9222-dcb3004fc9f9.png)

**Comment by chiefmc** [comment]
Same here... Can't get this to work with `awesome-typesctipt-loader`

**Comment by mblandfo** [comment]
Yep. Trying to upgrade from 2.2.4 makes my .d.ts file almost empty.

**Comment by MeirionHughes** [comment]
pretty much having to run a separate gulp build just for the declarations; ts-loader isn't great either and cannot exlcude test files. :/

**Comment by QuantumInformation** [comment]
Hmm I was just about to add tests with ts-loader, are you sure about this @MeirionHughes ?

**Comment by QuantumInformation** [comment]
isn't there a spec in ts that tells tsc to ignore a file, like naming with _test in the filename?

**Comment by MeirionHughes** [comment]
@QuantumInformation 
```js
rules: [ { test: /\.ts?$/, exclude: [ path.resolve(__dirname, "test")  ], ... 
```
... had no effect. 
Unfortunately, I cannot use exclude in the tsconfig because its used used by ts-node + mocha for testing. 
In addition: rather than get `./lib/index.d.ts` I'm getting './lib/src/index.d.ts` _et al_
```

I tried getting tsc to emit only the declarations, but that didn't work. In the end, it was simply easier to gulp it: 

```js
var gulp = require('gulp');
var gulpts = require('gulp-typescript');
var typescript = require('typescript');

gulp.task('typings', () => {
  var project = gulpts.createProject('tsconfig.json', {
    typescript: typescript
  });
  return gulp.src(['src/**/*.ts']).pipe(project()).dts.pipe(gulp.dest('./lib'));
});
```
